### ISSUE TITLE
Unrecognized option: :adapter (WebSocket::Driver::ConfigurationError)

### ISSUE THREAD

**Issue by n-rodriguez** [dotpromo/danthes#18]
Hi!

I've just install d'Anthès and got this error when lauching it :

```
dokku@services:~/deploy-it$ rackup danthes.ru -s thin -E development
/home/dokku/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.5.3/lib/websocket/driver.rb:166:in `block in validate_options': Unrecognized option: :adapter (WebSocket::Driver::ConfigurationError)
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.5.3/lib/websocket/driver.rb:164:in `each'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/websocket-driver-0.5.3/lib/websocket/driver.rb:164:in `validate_options'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/faye-1.1.1/lib/faye/adapters/rack_adapter.rb:29:in `initialize'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/danthes-2.0.0/lib/danthes.rb:112:in `new'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/danthes-2.0.0/lib/danthes.rb:112:in `faye_app'
	from /home/dokku/deploy-it/danthes.ru:15:in `block in <main>'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from /home/dokku/deploy-it/danthes.ru:in `new'
	from /home/dokku/deploy-it/danthes.ru:in `<main>'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/server.rb:272:in `start'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/lib/rack/server.rb:147:in `start'
	from /home/dokku/.rvm/gems/ruby-2.2.0/gems/rack-1.6.0/bin/rackup:4:in `<top (required)>'
	from /home/dokku/.rvm/gems/ruby-2.2.0/bin/rackup:23:in `load'
	from /home/dokku/.rvm/gems/ruby-2.2.0/bin/rackup:23:in `<main>'
	from /home/dokku/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/dokku/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by simonoff** [comment]
As workaround you can limit `websocket-driver` to `0.5.0` version.
I will fix this as soon as possible.

**Comment by simonoff** [comment]
@n-rodriguez fixed

**Comment by n-rodriguez** [comment]
Thank you!
